### ISSUE TITLE
咨询个关于xposed的问题

### ISSUE THREAD

**Issue by JamesLiAndroid** [iweizime/wechat#4]
我有一个问题想请教下，求指教。

有一个类a，继承自抽象类b<T>，类b<T>下有个getItem方法，这个getItem方法应该如何去hook？

我尝试直接用classloader加载b类，然后hook这个getItem方法, 最终不成功！

**Comment by iweizime** [comment]
可惜我也不会写xposed的插件，平时hook都是用的frida
